### ISSUE TITLE
Reducing SNR doesn't impact BER

### ISSUE THREAD

**Issue by rajatbh21** [MahmudulAlam/A-Complete-Digital-Communication-System#1]
Neither in BPSK, BASK reducing SNR is changing the BER. BER is always 0 which is impractical. Seems like a broken functionality.

**Comment by trueidiot7** [comment]
I find this bizarre too.

**Comment by MahmudulAlam** [comment]
@rajatbh21 @trueidiot7 
BPSK, BASK are the methods of modulation, they do not directly impact the bit error rate. The main source of bit error in any digital communication system is the channel. Channel adds white gaussian noise which makes the signal noisy. To see the impact, you have to change the signal to noise [(SNR) ratio](https://github.com/MahmudulAlam/A-Complete-Digital-Communication-System/blob/83e0fbc7b31b3f6dfa9f21cb5bc26a0c70781dbc/main_code.m#L13).

I also made an analysis on the effect of noise in the system, [see page 10 of the report](https://drive.google.com/file/d/1DXh3Bbg7VcpkuEDUYJxg1ooOJvkIway9/view). With different modulation methods, bit error rate changes for SNR less than -5.
